___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [ ]:
import numpy as np

### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [ ]:
my_list = [5, 10, 15, 20, 25]
my_list = np.array(my_list)
my_list

array([ 5, 10, 15, 20, 25])

In [ ]:
my_list = np.arange(5, 26, 5)
my_list

array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros. 

In [ ]:
zeros = np.zeros([5,5])
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [ ]:
ones = np.ones([4,4], dtype = int)
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [ ]:
ones = np.full_like(ones, 7)
ones

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [ ]:
sevens = np.full([4,4], 7)
sevens

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive). 

In [ ]:
arr = np.arange(2,17,2, dtype = int)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [ ]:
arr_2 = np.reshape(np.arange(0,25), (5,5))
arr_2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [ ]:
arr_3 = np.reshape(np.linspace(0,24,25), (5,5))
arr_3

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

### 10. Create randomly 5 numbers with numpy.

In [ ]:
random_array = np.random.randint(5, size = 5,)
random_array

array([2, 3, 3, 0, 4])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [ ]:
random_array = np.random.randn(5,5)
random_array

array([[ 1.13332223,  0.26425728,  0.69007832,  1.04570355, -0.09720214],
       [ 0.75285172,  1.98982155, -2.25739493,  0.54504887,  0.98856697],
       [ 1.69114677,  1.61546717, -0.06212632,  0.78964342,  0.8635507 ],
       [ 0.17676839,  2.27731808, -0.55657802, -0.57945791,  0.13435892],
       [ 1.91670137, -1.00434951,  0.27226996, -0.21616848,  0.04027832]])

In [ ]:
np.std(random_array)

1.0038800785236883

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [ ]:
random_int = np.random.randint(20,50, size = (3,4))
random_int

array([[23, 49, 47, 46],
       [36, 39, 38, 42],
       [33, 47, 32, 42]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [ ]:
ranarr = np.random.randint(0,100, size=48).reshape(6,8)
ranarr

array([[58, 17, 44, 94, 63, 26, 32, 46],
       [97, 30, 52, 78, 77, 30, 35, 47],
       [44, 18, 10, 28, 47, 42, 31, 40],
       [92, 61, 42, 21, 85, 90,  6, 50],
       [47, 99, 25, 17, 66, 68, 44, 86],
       [ 4, 16, 87, 86, 48, 31, 62, 90]])

In [ ]:
ranarr = np.arange(48).reshape(6,8)
ranarr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [ ]:
np.random.shuffle(ranarr)
ranarr

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [ ]:
ranarr = np.random.randint(1, [10, 50, 100, 150, 200, 250, 300, 350], size = (6,8))
ranarr

array([[  3,  39,  56, 141,  37, 245,  38, 157],
       [  8,   5,  75,  15, 162,  64, 179, 129],
       [  7,  41,  25,  62, 127, 101,   5,  63],
       [  9,   8,  79,  73,  90,  35,  51, 129],
       [  6,  42,  75,  32,  23,   7, 296, 178],
       [  5,  46,  21,  84, 117, 135,  34,   7]])

In [ ]:
ranarr = np.random.randint(0,100, size=48).reshape(-1,8)
ranarr

array([[56, 39, 55, 29, 71, 34, 76, 18],
       [36, 59, 48, 92, 28, 89, 32, 51],
       [33, 69, 27, 74, 29, 28,  7, 76],
       [27, 64, 25, 25, 97, 75, 89, 15],
       [33,  1, 62, 64, 13, 64,  7, 88],
       [ 7, 86, 11, 38, 73, 28, 88, 81]])

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [ ]:
mat = np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [ ]:
mat = np.array([[ 1, 2, 3, 4], [ 5, 6, 7, 8], [ 9, 10, 11, 12], [13, 14, 15, 16]])
slice_mat = mat[1:3,1:3]
slice_mat

array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [ ]:
slice2_mat = mat[0:,0:1]
slice2_mat

array([[ 1],
       [ 5],
       [ 9],
       [13]])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [ ]:
slice3_mat = mat [1:2,::2]
slice3_mat

array([[5, 7]])

### 17.Assign 77 to every cell in 3rd column.

In [ ]:
slice4_mat = mat[0:,2:3]=77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [ ]:
slice5_mat = mat[(1,3),(0,2)]
slice5_mat

array([ 5, 77])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [ ]:
slice6_mat = mat[1::2,0::2]
slice6_mat

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [ ]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
# LET US FIND THE VALUES SMALLER THAN 10 IN "mat" 
mat[mat < 10]

array([1, 2, 4, 5, 6, 8, 9])

In [ ]:
# LET US FIND THE VALUES BIGGER THAN 12 IN "mat" 
mat[mat > 12]

array([77, 77, 77, 13, 14, 77, 16])

In [ ]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat" 
sum_mat = mat[mat < 10] + mat[mat > 12]
sum_mat

array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [ ]:
# YOUR CODE IS HERE 
np.std(sum_mat)

29.700546274093877

### 22. Get the sum of the 2nd column in the original "mat".

In [ ]:
# LET US REMEMBER OUR ARRAY OF "mat" 
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
# LET OBTAIN THE ORIGINAL ARRAY OF "mat" 
mat = np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
# YOUR CODE IS HERE 
np.sum(mat[::,1:2])

32

### 23. Get the median, mean and std of 3rd column in "mat".

In [ ]:
# LET US REMEMBER OUR ARRAY OF "mat" 
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE 
third_column = mat[::,2:3]
third_column

array([[ 3],
       [ 7],
       [11],
       [15]])

In [ ]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW? 
third_row = mat[2:3,::]
third_row

array([[ 9, 10, 11, 12]])

In [ ]:
# LET US GET MEDIAN VALUE 
print(f"{np.median(third_column)} & {np.median(third_row)}")

9.0 & 10.5


In [ ]:
# LET US GET MEAN VALUE 
print(f"{np.mean(third_column)} & {np.mean(third_row)}")

9.0 & 10.5


In [ ]:
# LET US GET STANDART DEVIATION (std) VALUE 
print(f"{np.std(third_column)} & {np.std(third_row)}")

4.47213595499958 & 1.118033988749895


## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/sample_data/Salaries.csv")
df

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

In [ ]:
df = pd.read_csv("/content/sample_data/Salaries.csv")

In [ ]:
df.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [ ]:
df.sample()

Id   EmployeeName            JobTitle   BasePay  OvertimePay  OtherPay  \
361  362  GHODSI DAVARY  NURSING SUPERVISOR  183040.0          0.0  10250.24   

     Benefits   TotalPay  TotalPayBenefits  Year  Notes         Agency  Status  
361       NaN  193290.24         193290.24  2011    NaN  San Francisco     NaN

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [ ]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS  

# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [ ]:
# YOUR CODE IS HERE 



In [ ]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 



In [ ]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 



### Print out max and avg values in the column of "Totalpay".

In [ ]:
# LET US FIND THE MAXIMUM TOTALPAY

# YOUR CODE IS HERE 



In [ ]:
# LET US FIND THE AVERAGE TOTALPAY

# YOUR CODE IS HERE 



### How many records in the TotalPay column are there bigger than avg TotalPay?

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [ ]:
# YOUR CODE IS HERE 



### How much does ALBERT PARDINI make money (including benefits)?

In [ ]:
# YOUR CODE IS HERE 



### Who is the lowest paid person?

In [ ]:
# YOUR CODE IS HERE 



### What are the unique Jobs in dataset?

In [ ]:
# YOUR CODE IS HERE 



### List the top 3 least common Jobs in the dataset.

In [ ]:
# YOUR CODE IS HERE 



### How many people earned more than avg in 2012?

In [ ]:
# YOUR CODE IS HERE 



### How many people have a title of Manager in their jobs?

In [ ]:
# USE APPLY FUNCTION

# YOUR CODE IS HERE 



### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________